@startuml

state A {
    state B {
        state C
    }
}
state End <<end>>

state A : entry/ print("Entered State A")
state A : exit/ print("Exited State A")
state B : entry/ print("Entered State B")
state B : exit/ print("Exited State B")
state C : entry/ print("Entered State C")
state C : exit/ print("Exited State C")

[*] --> C
C --> End

@enduml