@startuml


state POWERED_OFF : entry/ print("Entered POWERED_OFF")
state POWERED_ON : entry/ print("Entered POWERED_ON")
state POWERED_ON {
    state PROGRAM_SELECT : entry/ self.program = input("Select program (1=Wash Cycle, 2=Dry Cycle, 3=Wash and Dry Cycle): ")
    state PROGRAM_SELECT : exit/ print(f"Starting program {self.program}")
    state WASHING : entry/ print("Washing..")
    state RINSING : entry/ print("Rinsing..")
    state SPINNING : entry/ print("Spinning..")
    state do_drying_choice <<choice>>
    state DRYING : entry/ print("Drying..")
    state PROGRAM_ENDED : entry/ print("Program ended")
    state exit <<exitPoint>>
}

[*] --> POWERED_OFF
POWERED_OFF --> POWERED_ON : /print("Powering on..")

state POWERED_ON {
    [*] --> PROGRAM_SELECT
}
PROGRAM_SELECT --> WASHING : [self.program == "1" or self.program == "3"]
PROGRAM_SELECT --> DRYING : [self.program == "2"]
PROGRAM_SELECT --> PROGRAM_SELECT : /print("Program not recognised")

WASHING --> RINSING
RINSING --> SPINNING
SPINNING --> do_drying_choice
do_drying_choice --> DRYING : [self.program == "3"]
do_drying_choice --> PROGRAM_ENDED
DRYING --> PROGRAM_ENDED

PROGRAM_ENDED --> exit
exit --> [*]


@enduml