# Production rules
# Used as a design aid only - not strictly valid EBNF!

state_declaration = KEYWORD_STATE NAME [STEREOTYPE] NEWLINE |
                    KEYWORD_STATE QUOTATION LABEL QUOTATION KEYWORD_AS NAME [STEREOTYPE] NEWLINE |
                    KEYWORD_STATE NAME [STEREOTYPE] OPEN_CURLY_BRACKET NEWLINE state_declaration CLOSE_CURLY_BRACKET NEWLINE

state_transition = (NAME | INITIAL_FINAL_STATE) ARROW (NAME | INITIAL_FINAL_STATE) [STEREOTYPE] NEWLINE |
                   (NAME | INITIAL_FINAL_STATE) ARROW (NAME | INITIAL_FINAL_STATE) [STEREOTYPE] COLON LABEL NEWLINE

note_declaration = KEYWORD_NOTE (KEYWORD_LEFT_OF | KEYWORD_RIGHT_OF) NAME COLON LABEL NEWLINE |
                   KEYWORD_NOTE (KEYWORD_LEFT_OF | KEYWORD_RIGHT_OF) NAME NEWLINE {LABEL NEWLINE} KEYWORD_END_UML KEYWORD_NOTE NEWLINE |
                   KEYWORD_NOTE QUOTATION LABEL QUOTATION KEYWORD_AS NAME NEWLINE